# Generated by Django 4.0.5 on 2022-06-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.SlugField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('joinDate', models.DateField()),
                ('exitDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'member',
            },
        ),
    ]
