# Generated by Django 4.0.5 on 2022-06-26 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_member_telegramid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('workingDayOpenTime', models.TimeField()),
                ('workingDayCloseTime', models.TimeField()),
                ('holidayOpenTime', models.TimeField()),
                ('holidayCloseTime', models.TimeField()),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('wardenName', models.CharField(max_length=100)),
                ('wardenNumber', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Hostel',
                'verbose_name_plural': 'Hostels',
                'db_table': 'hostel',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='member',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SpecialDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('open', models.TimeField()),
                ('close', models.TimeField()),
                ('isClosed', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.group')),
            ],
            options={
                'verbose_name': 'Special Date',
                'verbose_name_plural': 'Special Dates',
                'db_table': 'membership_specialdate',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.group'),
        ),
        migrations.AddField(
            model_name='member',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.hostel'),
        ),
    ]
