# Generated by Django 4.0.5 on 2022-11-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_hostel_wardenname_alter_hostel_wardennumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='holidayCloseTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='holidayOpenTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='workingDayCloseTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='workingDayOpenTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='wardenName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Warden Name'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='wardenNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Warden Number'),
        ),
    ]
