# Generated by Django 4.0.5 on 2023-02-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_group_holidayclosetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='lastSeen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
