# Generated by Django 4.0.5 on 2022-06-25 16:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiFiAttendanceDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('macAddress', models.CharField(max_length=17, unique=True)),
                ('timestampAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member')),
            ],
        ),
        migrations.CreateModel(
            name='WiFiAttendanceLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ipAddress', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.wifiattendancedevice')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member')),
            ],
            options={
                'verbose_name': 'WiFi Attendance Log',
                'verbose_name_plural': 'WiFi Attendance Logs',
                'db_table': 'wifi_attendance_log',
            },
        ),
    ]
