# Generated by Django 4.0.5 on 2022-10-03 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('macAddress', models.CharField(max_length=17, unique=True)),
                ('bluetoothAddress', models.CharField(max_length=50, unique=True)),
                ('timestampAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member')),
            ],
            options={
                'verbose_name': 'Attendance Device',
                'verbose_name_plural': 'Attendance Devices',
                'db_table': 'attendance_device',
            },
        ),
        migrations.CreateModel(
            name='AttendanceTracker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='WIFI', max_length=10)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Attendance Tracker',
                'verbose_name_plural': 'Attendance Trackers',
                'db_table': 'attendance_tracker',
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='WIFI', max_length=10)),
                ('ipAddress', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendancedevice')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member')),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'verbose_name_plural': 'Attendance Logs',
                'db_table': 'attendance_log',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('type', models.CharField(default='BUNK', max_length=25)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'db_table': 'leave_request',
                'unique_together': {('member', 'date')},
            },
        ),
    ]
