# Generated by Django 4.0.5 on 2022-10-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancedevice',
            name='bluetoothAddress',
        ),
    ]
