# Generated by Django 4.0.5 on 2022-06-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_member_telegramid'),
        ('attendance', '0003_leaverequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaverequest',
            unique_together={('member', 'date')},
        ),
    ]
