# Generated by Django 4.0.5 on 2022-06-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_leaverequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='type',
            field=models.CharField(default='BUNK', max_length=25),
        ),
    ]
