# Generated by Django 4.0.5 on 2022-11-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_group_holidayclosetime_and_more'),
        ('attendance', '0004_attendancelog_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDateLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('minutes', models.PositiveSmallIntegerField()),
                ('logs', models.JSONField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member')),
            ],
            options={
                'verbose_name': 'Attendance Date Log',
                'verbose_name_plural': 'Attendance Date Logs',
                'db_table': 'attendance_date_log',
                'unique_together': {('member', 'date')},
            },
        ),
    ]
