# Generated by Django 4.0.5 on 2022-06-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancedevice_attendancelog_and_more'),
        ('attendance', '0005_leaverequest_type'),
    ]

    operations = [
    ]
