# Generated by Django 4.0.5 on 2022-11-11 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_delete_attendancelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancedatelog',
            name='minutes',
        ),
    ]
