# Generated by Django 4.0.5 on 2022-11-11 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('attendance', '0007_remove_attendancedatelog_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTrackerLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('logs', models.JSONField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apiclient')),
            ],
            options={
                'verbose_name': 'Attendance Tracker Log',
                'verbose_name_plural': 'Attendance Tracker Logs',
                'db_table': 'attendance_tracker_log',
                'unique_together': {('timestamp', 'client')},
            },
        ),
    ]
