# Generated by Django 4.0.5 on 2023-02-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendancetrackerlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancedatelog',
            options={'ordering': ['-lastSeen', '-date'], 'verbose_name': 'Attendance Date Log', 'verbose_name_plural': 'Attendance Date Logs'},
        ),
        migrations.AddField(
            model_name='attendancedatelog',
            name='lastSeen',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
