# Generated by Django 4.0.5 on 2023-02-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendancedatelog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancedatelog',
            options={'ordering': ['-date', '-lastSeen', 'member__name'], 'verbose_name': 'Attendance Date Log', 'verbose_name_plural': 'Attendance Date Logs'},
        ),
    ]
