# Generated by Django 4.0.5 on 2023-02-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_attendancedatelog_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedatelog',
            name='firstSeen',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
